---
title: "ggspatial: Spatial data framework for ggplot2"
output: github_document
---

Spatial data plus the power of the `ggplot2` framework means easier mapping.

## Installation

The package is available on CRAN, and can be installed using `install.packages("ggspatial")`. The development version can be installed via `devtools`.

```{r, eval=FALSE}
install.packages("devtools") # if devtools isn't installed
devtools::install_github("paleolimbot/ggspatial")
```

## Introduction

Currently, this package is in mega overhaul mode.

```{r}
library(tidyverse)
library(ggspatial)
load_longlake_data()
```

## Using `df_spatial()`

```{r}
df_spatial(longlake_depthdf)
```


```{r}
df_spatial(longlake_depth_raster)%>%
  filter(!is.na(band1))
```


```{r fig-df-spatial-raster}
ggplot() +
  geom_raster(
    aes(x, y, fill = band1), 
    data = df_spatial(longlake_depth_raster) %>% filter(!is.na(band1))
  ) +
  geom_point(aes(x, y), data = df_spatial(longlake_depthdf)) +
  coord_fixed()
```

## Using `layer_spatial()`

```{r fig-layer-spatial-raster}
ggplot() +
  layer_spatial(longlake_osm) +
  layer_spatial(longlake_depthdf)
```

```{r fig-layer-annotation-raster}
ggplot() +
  annotation_spatial(longlake_osm) +
  layer_spatial(longlake_depthdf)
```
