
#' Add a bounding box to a map
#'
#' To include a bounding box without drawing it, use [shadow_spatial()] on the
#' original object.
#'
#' @param data A bounding box generated by [sf::st_bbox()]
#' @inheritParams layer_spatial
#'
#' @export
#'
#' @examples
#' library(ggplot2)
#' load_longlake_data()
#' ggplot() +
#'   layer_spatial(sf::st_bbox(longlake_waterdf)) +
#'   layer_spatial(longlake_depthdf)
#'
#' # use shadow_spatial() to include the geographic area of an object
#' # without drawing it
#' ggplot() +
#'   shadow_spatial(longlake_waterdf) +
#'   layer_spatial(longlake_depthdf)
#'
layer_spatial.bbox <- function(data, mapping = aes(), ...) {
  layer_spatial(sf_bbox_to_sf(data), mapping = mapping, ...)
}

#' @rdname layer_spatial.bbox
#' @export
annotation_spatial.bbox <- function(data, mapping = aes(), ...) {
  annotation_spatial(sf_bbox_to_sf(data), mapping = mapping, ...)
}

#' @rdname layer_spatial
#' @export
shadow_spatial.bbox <- function(data) {
  layer_spatial.bbox(data, colour = NA, fill = NA)
}

sf_bbox_to_sf <- function(data) {
  xs <- data[c("xmin", "xmin", "xmax", "xmax", "xmin")]
  ys <- data[c("ymin", "ymax", "ymax", "ymin", "ymin")]
  poly <- sf::st_polygon(list(cbind(xs, ys)))
  geometry <- sf::st_sfc(poly, crs = sf::st_crs(data))
  tbl <- tibble::tibble(geometry = geometry)
  sf::st_sf(tbl)
}
