

guess_projection <- function(bbox, quiet=FALSE) {
  # copied from prettymapr scalebar function
  extents <- c(bbox[1,1], bbox[1, 2], bbox[2,1], bbox[2,2])
  # check for valid lat/lon in extents
  if(extents[1] >= -180 &&
     extents[1] <= 180 &&
     extents[2] >= -180 &&
     extents[2] <= 180 &&
     extents[3] >= -90 &&
     extents[3] <= 90 &&
     extents[4] >= -90 &&
     extents[4 <= 90]) {
    if(!quiet) message("Autodetect projection: assuming lat/lon (epsg:4326)")
    sp::CRS("+init=epsg:4326")
  } else {
    # else assume google mercator used by {OpenStreetMap} (epsg 3857)
    if(!quiet) message("Audotdetect projection: assuming Spherical Mercator (epsg:3857)")
    sp::CRS("+init=epsg:3857")
  }
}

# stat to transform coordinates
StatProject <- ggplot2::ggproto("StatProject", ggplot2::Stat,

    # TODO: this should really be in compute_layer, which has
    # slightly different arguments
    compute_panel = function(data, scales, crsfrom=NULL, crsto=NULL) {
      # load rgdal namespace
      requireNamespace("rgdal", quietly = TRUE)

      # guess missing coordinate systems
      if(is.null(crsfrom) || is.na(rgdal::CRSargs(crsfrom))) {
        crsfrom <- guess_projection(sp::bbox(cbind(data$x, data$y)))
      }

      # default is actually to "unproject", for use with ggmap/coord_map
      if(is.null(crsto) || is.na(rgdal::CRSargs(crsto))) {
        crsto <- sp::CRS("+init=epsg:4326")
        if(crsfrom@projargs != crsto@projargs) {
          message("Converting coordinates to lat/lon (epsg:4326)")
        }
      }

      # if crs from and to are equivalent, return the original data
      if(crsfrom@projargs == crsto@projargs) {
        return(data)
      } else {
        coords <- coordinates(sp::spTransform(
          sp::SpatialPoints(
            sp::coordinates(cbind(data$x, data$y)), crsfrom), crsto))
        data$x <- coords[,1]
        data$y <- coords[,2]
        return(data)
      }
    },

    required_aes = c("x", "y")
)

#' Statisitc to project coordinates
#'
#' Projects coordinates using rgdal/sp. For use with \link{geom_spatial}. Takes params
#' \code{crsfrom} and \code{crsto}, both generated by \code{sp::CRS()} or \code{NULL}.
#' If \code{NULL}, \code{crsto} is assumed to be EPSG:3857 (Spherical Mercator) and
#' \code{crsto} is assumed to be EPSG:4326 (Lat/Lon).
"StatProject"
